### ISSUE TITLE
add an init/sync options

### ISSUE THREAD

**Issue by dpastoor** [A2-ai/setup-rv#2]
something along the lines of

```
- name: Install the latest version of rv
  uses: a2-ai/setup-rv@v1
  with:
      init: true
```
